name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: servicebus
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: servicebus-sqledge
      MSSQL_SA_PASSWORD: ChangeMynam3
      ACCEPT_EULA: y
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
    container_name: servicebus-sqledge
    image: mcr.microsoft.com/azure-sql-edge:latest
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: ChangeMynam3

networks:
  sb-emulator:
