version: '3'
services:
  gitlab:
    # Username: root.
    # Password: Get from:
    # docker exec -it gitlab grep 'Password' /etc/gitlab/initial_root_password
    container_name: gitlab
    image: gitlab/gitlab-ce:16.11.0-ce.0
    restart: always
    ports:
      - "10000:80"
      - "10002:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
