services:
  mssql:
    container_name: mssql
    build:
      context: .
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mssqlADMIN1234,.
    ports:
      - 1433:1433
    hostname: mssql
    platform: linux/amd64
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_logs:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets
  mssql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql-edge
    restart: always
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=mssqlADMIN1234,.
    ports:
      - 1433:1433
    hostname: mssqledge

volumes:
  mssql_data:
  mssql_logs:
  mssql_secrets:
