services:
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: aspire
    restart: always
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888"
      - "4317:18889"
